export enum FileName {
    BUG_REPORT = 'bug_report.md',
    FEATURE_REQUEST = 'feature_request.md',
    PULL_REQUEST = 'pull_request_template.md',
    BUG = 'Bug.md',
    CI_TEMPLATE = 'example-ci.yml',
    FEATURE_PROPOSAL = 'Feature proposal.md',
    MERGE_REQUEST = 'merge_request_template.md',
    CODE_OF_CONDUCT = 'CODE_OF_CONDUCT.md',
    CONTRIBUTING = 'CONTRIBUTING.md',
    LICENSE = 'LICENSE',
    README = 'README.md',
    TODO = 'TODO.md',
    CHANGELOG = 'CHANGELOG.md',
    SECURITY = 'SECURITY.md',
    APPSPEC = 'appspec.yml',
    BUILDSPEC = 'buildspec.yml',
    DOCKERFILE = 'Dockerfile',
    CODEQL_ANALYSIS = 'codeql-analysis.yml',
    NODE_CI = 'nodejs.yml',
}